hyperparameters:
  client:
    batch_size: 256
    local_epochs: 10
    loss: CrossEntropyLoss
    optimizer:
      name: AdamW
      lr: 1e-04
      # momentum: 0.9
      weight_decay: 1.0e-04
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: model.tabular_models.Custom_MLP
  net_args:
    input_dim: 11
    output_size: 2
  server:
    weighted: true
name: fluke.algorithms.scaffold.SCAFFOLD